### ISSUE TITLE
Incorrect hover feedback for dark and light buttons when disabled

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/bootstrap#524]
### Description

Buttons have a hover effect, each one differs based on the selected theme. However, all of them get's a fainted look when it disabled. I have found recently that both `.btn-dark` and `.btn-light` incorrectly shows a hover background when they are disabled which is an incorrect behaviour.

### Expected behaviour

Hover effects should not be applied for disabled buttons so that it doesn't indicate to the user that they are interact-able.

### Possible causes

I've noticed that styles like this were applied in 2 stages.
- First styles of the buttons where applied for hover state
- Second these styles are disabled when the button are disabled

I suggest that you define the rules once and exclude the undesired states

And example taken from the code observed is this:
```scss
// Instead of this selector
.btn-light:hover {
// Use this
.btn-light:not(:disabled):hover {
    color: #000;
    background: #fff;
    border-color: #fff !important;
}
```
